framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
        packages:
          admin:
            json_manifest_path: '%kernel.project_dir%/bundle/w3des/AdminBundle/Resources/public/build/manifest.json'