
doctrine_migrations:
    migrations_paths:
      'App\Migrations': '%kernel.project_dir%/migrations'
    organize_migrations: BY_YEAR
    em: default
    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: 'doctrine_migration_versions'
            version_column_name: 'version'
            version_column_length: 190
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'
    all_or_nothing: true
    check_database_platform: true