# See https://github.com/excelwebzone/EWZRecaptchaBundle for full configuration
ewz_recaptcha:
    public_key:  '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    private_key: '%env(GOOGLE_RECAPTCHA_SECRET)%'
    ajax: false
    version: 3
